baseURL: "https://mihaya03.github.io/mihaya-note/"
languageCode: ja
title: mihaya note
theme: beautifulhugo

params:
  KaTeX: true

module:
  imports:
    - path: "beautifulhugo"

taxonomies:
  category: "categories"
  tag: "tags"
  archive: "archives"

menus:
  main:
    - identifier: "terms"
      name: "Categories"
      url: "/categories/"
      weight: 10 # The wieght determines the order of the menu items.

    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 20 # The wieght determines the order of the menu items.

author: 
  github: https://github.com/mihaya03
  
  
